do not require `mode: taint` in new style taint rule
returntocorp/semgrep-interfaces pull request #63
Opened 2023-03-15 00:20 UTC by brandonspark

This PR just makes it so `mode: taint` is not required in new-style taint rules.

2023-03-15 00:21 UTC, brandonspark commented
It seems I have some of your changes @mjambon, it looks like they weren't pushed to the main repo.

2023-03-15 07:34 UTC, aryx commented
Please make a PR with just your change.

2023-03-15 07:34 UTC, aryx requested changes
remove the stuff from martin in this PR.

2023-03-15 19:50 UTC, brandonspark commented
@aryx is it not the case that even if i did, we wouldn't be able to update our version of `semgrep-interfaces` within `semgrep` because there would be a conflict?

2023-03-16 03:39 UTC, brandonspark commented
well, i guess we'll just keep the unmerged changes on the `semgrep` side. i suppose at some point we should push them to `semgrep-interfaces`, though.

2023-03-16 09:00 UTC, aryx approved these changes

2023-03-16 09:00 UTC, merged